os: linux
dist: bionic
language: ruby
rvm:
- 2.7.2
cache: bundler

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

jobs:
  include:
    - stage: Run Tests
      script: ./script/run_jekyll.sh
      name: "Run jekyll"
    - script: ./script/validate_json.rb
      name: "Validate JSON"
    - script: ./script/ping_websites.rb
      name: "Ping websites"
    - script: ./script/check_files_formatting.sh
      name: "Check Files Formatting"
